# Starter pipeline
# Start with a minimal pipeline that you can customize to build and deploy your code.
# Add steps that build, run tests, deploy, and more:
# https://aka.ms/yaml

trigger:
- master

pool:
  vmImage: 'Ubuntu-16.04'

steps:
# - script: echo Hello, world!
#   displayName: 'Run a one-line script'

# - script: |
#     echo Add other tasks to build, test, and deploy your project.
#     echo See https://aka.ms/yaml
#   displayName: 'Run a multi-line script'

- task: DotNetCoreInstaller@0
  inputs:
    version: '2.2.105'

- script: dotnet restore

- task: DotNetCoreCLI@2
  displayName: Build
  inputs:
    command: build
    #projects: '**/*.csproj'
    #arguments: '--configuration Debug'

- task: DotNetCoreCLI@2
  displayName: Test
  inputs:
    command: test
    projects: 'pipelines-dotnet-core-test/pipelines-dotnet-core-test.csproj'
    arguments: '--collet "Code coverage"'
    #arguments: '--configuration Debug'

